### ISSUE TITLE
Would you mind to share the STM32 project source  showed on youtube?

### ISSUE THREAD

**Issue by qwert1213131** [lvgl/lvgl#12]
https://www.youtube.com/watch?v=DcJdK137WKM
That is amazing!

**Comment by kisvegabor** [comment]
Do you mean the Eclipse project or the source code of the GUI?

**Comment by qwert1213131** [comment]
it is about the code ported to stm32.
i have the stm32f429 disco board.
i can't make the gui worked on stm32.
thanks!

**Comment by kisvegabor** [comment]
I've added a download button for the project tothe bottom of this page: 
http://www.gl.littlev.hu/blog/8/embedded-gui-on-stm32-discovery-board-with-littlev-graphicslibrary

Please send me feedback whether it is working or facing any problems.

**Comment by qwert1213131** [comment]
Thank you very much！

**Comment by kisvegabor** [comment]
Had you time to try it? And was it working?

**Comment by ghost** [comment]
Hi, I tried that on the same STM board, but it is lagging a lot. Where could be the problem? Thank you

**Comment by kisvegabor** [comment]
I've updated the project. Please, check it again.

**Comment by ghost** [comment]
Thx now it´s working perfectly. Maybe i just did something wrong because i use IAR ide so i had to convert whole project. Please do you have some demo project or code of aplications (like sys. monitor) in use? I cant make them to work.
Thank you and your library is awesome. Great work! 👍

**Comment by kisvegabor** [comment]
Your welcome! Good to hear that!

I don't have a different project for the applications because it is very easy to make them work. Actually in the project you are using the applications are enabled and initalized just the demo creates an other screen so the applications are not visible. 

You just need to comment out the `stm32_test_init();` in `main.c` to see the applications. So far only a few applications are exists however I constantly create new ones. 

Please, check the bottom section in `lv_conf.h` where you can find the application related configurations.

If you are interested in the applications please start an other thread for them. Now, because the demo project seems working for you too, if you agree I close this issue.
