### ISSUE TITLE
small button is hard to drag.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1591]
I created a small button size(20*20), and set draggable. but its hard  to drag.
[smallbtn_hard_to_drag.zip](https://github.com/lvgl/lvgl/files/4797447/smallbtn_hard_to_drag.zip)

**Comment by kisvegabor** [comment]
Try `lv_obj_set_protect(btn, LV_PROTECT_PRESS_LOST)`

**Comment by incity** [comment]
It's OK , but why need this?

**Comment by embeddedt** [comment]
> It's OK , but why need this?

It's because your finger moves off the button before the button can catch up to your finger's position. Setting `LV_PROTECT_PRESS_LOST` ensures that the button continues receiving input events after your finger moves off of it.

This is the same way it works in HTML5/JavaScript. Typically the dragging is controlled by the window (and not the button itself), but the principle is the same - events are tracked even when your  finger moves outside of the button's bounding box.

**Comment by incity** [comment]
thanks, by the way, for the textarea if i put the mouse on the text to start drag, it can not be dragged. but if i let the mouse leave the text and it can be dragged. how to solve this?

**Comment by kisvegabor** [comment]
We use GitHub Issues for development-related discussions.

Please ask your question in the [Forum](https://forum.lvgl.io) to make it visible for a larger community. You can simply log in with your GitHub account.

**Comment by embeddedt** [comment]
I think the original question is answered so I'll close this issue.
