### ISSUE TITLE
Letter space rendering is inconsistent

### ISSUE THREAD

**Issue by BenQoo** [lvgl/lvgl#168]
The rendering letter space could be inconsistent on certain characters.
But, for the most of characters space are fine, so to adjust `letter_space` of `lv_style_t` could not solve this issue properly.

* LVGL version : 5.1
* Font Name : [NotoSans-SemiCondensedMedium.ttf](https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip)
* Height :18 
* [lv_font_notosans_semicondensedmedium_18.zip](https://github.com/littlevgl/lvgl/files/1818188/lv_font_notosans_semicondensedmedium_18.zip)

Please refer to the following screenshots
* Red arrows: space is too tight
* Blue arrows: space is too loose.

Screenshot
![100%](https://user-images.githubusercontent.com/29389982/37507264-9a4c8828-2928-11e8-8258-be5c1aff735d.png)
Screenshot with zoom in 600%
![600%](https://user-images.githubusercontent.com/29389982/37507313-d4c52794-2928-11e8-911d-987f4a277b79.png)

**Comment by kisvegabor** [comment]
Hi,

Thank you for the detailed report!

As I see you have used `style.text.letter_space = 0` so it should be no space between letters. If you look carefully the word "current" between 'r' and 'e' there is no space because 'r' has a very light pixel on the right and 'e' has light pixels on the left. 

This issue is typically solved by [Kerning](https://en.wikipedia.org/wiki/Kerning) but it is not implemented in LittlevGL yet. Kerning uses tables to modify the letter space based on letter pairs.

**Comment by BenQoo** [comment]
Hi,

Thanks for your explanation, I got it.

> As I see you have used style.text.letter_space = 0 so it should be no space between letters.

You're right. Because set `style.text.letter_space = 1` will make the space too loose, I tried to set it to zero before.
Please let me close this issue.

**Comment by kisvegabor** [comment]
Your welcome! :)
