### ISSUE TITLE
Porting LittlevGL to STM32f746 Discovery board

### ISSUE THREAD

**Issue by liubingyan123** [lvgl/lvgl#171]
any plane to port littlevgl to stm32f746 diccovery board?

**Comment by kl-cruz** [comment]
Hi, I'll try to prepare pull-request soon. Stay tuned!

**Comment by kl-cruz** [comment]
Well, it is proof-of-concept solution for this board. I do not use Eclipse as a software for code development so I cannot reproduce makefiles found in the other examples. Instead of that solution I have created Makefile based on the recipe found here: http://mcufreaks.blogspot.com/2013/03/customizable-makefile-for-gcc-arm.html .
Please let me know if You are interested in this code (I can prepare pull-request):
https://github.com/kl-cruz/lv_boards/tree/stm32f7_discovery_integration

**Comment by kisvegabor** [comment]
Hi Karol,

Yes I'm very interested in it! Thank you in advance!
I think Eclipse is easier for a lot of guys so if you don't mind I will "translate" your project to an Eclipse project.

I saw that you are using ChroArt too. It's great! Have you also  tested it ?

**Comment by kl-cruz** [comment]
Sure, I tested all the options. As You can see code needs to be refactored a little. I think I will do it today.

**Comment by kl-cruz** [comment]
Ok, cleaned a little bit. I am creating pull-request. Eclipse project can be good solution but please look at this line: 
https://github.com/kl-cruz/lv_boards/blob/stm32f7_discovery_integration/stm32f429_discovery_no_os/Release/makefile#L59

I do not know if it will work correctly.

**Comment by kisvegabor** [comment]
Thank you!
I will examine that line!

**Comment by kisvegabor** [comment]
As the project is already merged to lv_project repo I close this issue.

Thank you very much for sharing your project!
