### ISSUE TITLE
lv_switch visual state does not match logical state

### ISSUE THREAD

**Issue by HX2003** [lvgl/lvgl#1795]
**Describe the bug**

When clicking the switch repeatedly, the state does not correspond to the visual appearance.

**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally, this should work in the PC simulator unless the problem is specific to one platform.

**Expected behaviour**

**Screenshots**
![Screenshot (31)](https://user-images.githubusercontent.com/20015076/93320811-1874e500-f844-11ea-8410-3d83ab06d3f4.png)

**Additional context**

**Comment by embeddedt** [comment]
Confirmed using the demo on the website. I was not able to reproduce on STM32 - probably because the CPU takes so long to change themes that the extra clicks are not even registered.

**Comment by hedyhefty** [comment]
I have encountered the same problem...my solution was to disable the animation of the switch, and the problem seems not to occur again.

**Comment by kisvegabor** [comment]
I could reproduce the issue. 
I'm pretty sure it comes from the animation of the bar. I wonder if in the name of simplification we can go for a more simple bar animation handler (like previously). 

The current bar animation mechanism was invented to produce smooth animation even if the bar has a very small range (e.g. range = 0-3 but has width = 200 px).

So can we make the user to set a larger range (e.g. instead of 0-3 -> 0-300) and in 
- value change event scale the value
- release event snap to a valid value?

What do you think?

**Comment by embeddedt** [comment]
I'd rather keep the current animation; I think it's useful and keeps things simple for the user.

The issue seems to happen specifically when a previous animation is still in progress and a new one is started. Otherwise, the code works without problems. I think we should be able to fix it or at least add a workaround for rapid changes.

**Comment by kisvegabor** [comment]
I set the switch's anim time to 3000 in the widgets demo with `lv_switch_set_anim_time(sw, 3000);`.
With this, the issue is quite obvious. 

@embeddedt If I remember well this part was written by you. Could you take a look at it?

**Comment by embeddedt** [comment]
Yes; I'm currently working on a fix.

**Comment by kisvegabor** [comment]
Awesome :slightly_smiling_face:
