### ISSUE TITLE
change the btn state when user move between btns

### ISSUE THREAD

**Issue by Moo2017** [lvgl/lvgl#185]
I have 6 buttons and I want to display something once user press the left and right key and just move between the buttons. I tried to use btn state but it doesn't change and always has the Released state (0) .

**Comment by Masi2017** [comment]
@kisvegabor Ok thanks, I was wondering how many group we are allowed to create? If we want to have different screen and pages and each page has different items, is that possible to remove previous group or create new group? now I have a main menu including 6 menu so I need different action for each menu and I can not use matrix button and I have used 6 button, so I have to create new group otherwise with next and prev key it moves between all objects including the previous page (main menu). But I found that if I create multiple group after n time system crashes.

**Comment by Moo2017** [comment]
Thank you very much. It worked.
