### ISSUE TITLE
Add a function to remove a series from a chart

### ISSUE THREAD

**Issue by Rabdf** [lvgl/lvgl#1893]
A function to remove a series from a chart (counterpart to lv_chart_add_series ()) is missing yet.

**Comment by upbeat27** [comment]
I'm gonna piggy back on this and suggest a function for toggling series visibility.
Something like `lv_chart_show_series(bool show)`. Default would be `true` of course.
An example: https://www.flotcharts.org/flot/examples/series-toggle/index.html
Basically if there are a lot of series, it can be useful to hide some in order focus in on what you are interested in.
Right now you have to clear the series, and re-set all the data in order to achieve a similar result.

**Comment by kisvegabor** [comment]
I agree with both suggestions. 
Do you have time and interest to contribute to these feature?

**Comment by Rabdf** [comment]
I think I could write a function `lv_chart_remove_series ()`.
Adding a function like `lv_chart_show_series (bool show)` might be difficult as there is no flag attached to a series. Maybe we could change the color instead (to "invisible"); to make the series visible again one has to change the color to the one used before (or any other color).
Is there a kind of tutorial for code changes (how to create a fork, does anyone manage function names etc., and how to insert the changes into master)?

**Comment by embeddedt** [comment]
> Is there a kind of tutorial for code changes (how to create a fork, does anyone manage function names etc., and how to insert the changes into master)?

Of course! https://docs.lvgl.io/latest/en/html/contributing/index.html#pull-request

There's also a [coding style guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md), but you can probably pick up the most important things just by looking at the functions. I will complain in the code review if something is noticeably wrong. :wink:

**Comment by Rabdf** [comment]
#1948 adds `lv_chart_remove_series ()`.

**Comment by Rabdf** [comment]
#1952 adds `lv_chart_hide_series (..., bool hide)`.

**Comment by Rabdf** [comment]
#1952 merged into #1948

**Comment by kisvegabor** [comment]
The fieature is added
