### ISSUE TITLE
Incorrect date in Release notes

### ISSUE THREAD

**Issue by david-res** [lvgl/lvgl#1924]
v7.8.0 is stated to be released on 20.10.2020 - Just thought it would be worth noting, to not confuse users and get us over excited about the upcoming enhancements and bug fixes ;)

**Comment by embeddedt** [comment]
This file is behind... that's very strange. 7.7.2 was already released 5 days ago, and November 20th already passed, so that doesn't look like a typo. I'm not sure if the script tries to autogenerate the date but it does look like something messed up. I think December 1st would be the correct date here, so we'll go with that. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
Thanks for the fix. 
I type the dates by hand. It seems only the order of number was incorrect. "20.10" is almost "12.01" :laughing:  

I've applied a further fix for dd.mm.yyyy format.
https://github.com/lvgl/lvgl/commit/68300a5dece1df202654b3950a14a82314047d28

**Comment by embeddedt** [comment]
@kisvegabor I believe with your fix it is now scheduled for January 12, 2020 instead of December 1st, 2020. Could you double check?

**Comment by kisvegabor** [comment]
Oh, you are right. I got confused with the order...
I've reverted your version.
https://github.com/lvgl/lvgl/commit/5848aa59e591a49724c708165c57a46d4cdd557f
