### ISSUE TITLE
lvgl_fs_open + default FS_O_CREATE flag couldn't open files in RO filesystems

### ISSUE THREAD

**Issue by glory-man** [lvgl/lvgl#2195]
### Introduce the problem
I uses png files in my appl based on zephyr-rtos. png-decoder tries to open file 
    lv_fs_open(&f, fn, LV_FS_MODE_RD);

lvgl_fs_open (lvgl_fs.c) function that is called as a result sets default FS_O_CREATE flag/mode for fs_open
   int zmode = FS_O_CREATE;
plus FS_O_READ

My problem is that I am using read-only filesystem, mount-point of it has FS_MOUNT_FLAG_READ_ONLY flag. And fs_open return -EROFS. As a result the file cannot be opened.

For what purpose the FS_O_CREATE-flag is set when opening а file?

LVGL v7.6.1

**Comment by embeddedt** [comment]
This would be an issue with the Zephyr glue logic that you are using. LVGL itself only distinguishes between [opening for reading and writing](https://github.com/lvgl/lvgl/blob/3025101786ee62178737087bef97a8660782d39e/src/lv_misc/lv_fs.h#L54-L61) - there is no `O_CREAT` equivalent.

Nevertheless, I did some more research, and [according to POSIX](https://pubs.opengroup.org/onlinepubs/007908799/xsh/open.html):

> [EROFS] The named file resides on a read-only file system and either O_WRONLY, O_RDWR, O_CREAT (if file does not exist) or O_TRUNC is set in the oflag argument.

Therefore, it sounds like this might be a problem with Zephyr itself. The Zephyr docs themselves [state that](https://docs.zephyrproject.org/latest/reference/file_system/index.html#c.fs_open) `EROFS` should only get returned if you are "attempting to create a file" on a read-only file system. Since the file already exists, you are not really attempting to create it.
