### ISSUE TITLE
Adding widgets to a message box triggers assertion

### ISSUE THREAD

**Issue by higaski** [lvgl/lvgl#2494]
### Describe the bug
Adding widgets to a [message box](https://docs.lvgl.io/master/widgets/extra/msgbox.html) triggers an assertion.

### To Reproduce
The issue can easily be reproduced by taking the message box example and adding some other widget with the message box as parent parameter.
```c
static void event_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_current_target(e);
    LV_LOG_USER("Button %s clicked", lv_msgbox_get_active_btn_text(obj));
}

void lv_example_msgbox_1(void)
{
    static const char * btns[] ={"Apply", "Close", ""};

    lv_obj_t * mbox1 = lv_msgbox_create(NULL, "Hello", "This is a message box with two buttons.", btns, true);
    lv_obj_add_event_cb(mbox1, event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_center(mbox1);

    lv_obj_t* label = lv_label_create(mbox1);  /*Added label here!*/
}
```
  
The assertion I get is the following:
> [Error] (2.118, +756)    lv_btnmatrix_get_selected_btn: Asserted at expression: lv_obj_has_class(obj, &lv_btnmatrix_class) == true (Incompatible object type.)  (in lv_btnmatrix.c line #296)

**Comment by embeddedt** [comment]
Technically this is expected behavior. The message box assumes that its button matrix is the [last child](https://github.com/lvgl/lvgl/blob/20f186759664f31f07d6613ea8d77df256cd4597/src/extra/widgets/msgbox/lv_msgbox.c#L128-L131).

@kisvegabor I think the best way to solve this problem is to not depend on the index of the children at all, and just store their pointers in the message box structure ([like v7](https://github.com/lvgl/lvgl/blob/ac1fa649ca3e85bd94bff125fa6077d1c2acdc3e/src/lv_widgets/lv_msgbox.h#L50-L51)). We are really only saving 8 bytes per message box with the current approach; it's not worth it, in my opinion. I can't think of any applications where a lot of message boxes need to be created concurrently.

**Comment by kisvegabor** [comment]
This method really looks to fragile. I've pushed a fix to directly store the pointers of all 4 children.
