### ISSUE TITLE
Issues about using group and external keyboard

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#312]
Hi,
I have two issues about using group and external keyboard,and don't use "kb" object
1、How to delete chars of 'ta' object when using external keyboard？(such as a custom “del” key)

2、How to use a custom external keyboard “return” key to close a window(no focus is on btns of window) or delete some objects, can it be implemented with this library?I have no idea.

**Comment by kisvegabor** [comment]
Hi,

1. An `LV_GROUP_KEY_DEL` define is really missing.

2. So for example, you are typing in a text area, press "return" and you would like to close the window of the text area? If yes, then you can catch the "return" key in `indev_read` function and instead of setting it as the current key you can delete something. You can use the `lv_group_get_focused()` function to determine which object is focused.

I just added `LV_GROUP_KEY_DEL` and its handling to the Text area and done a minor update to be sure the delete of an object in `indev_read` won't break the library. The update is in the `beta` branch.

**Comment by as564335sa** [comment]
Hi,
Great! I'll try it later. Thanks!
