### ISSUE TITLE
Bug when style of 'ta' set up "lv_ta_set_one_line"

### ISSUE THREAD

**Issue by as564335sa** [lvgl/lvgl#319]
After call "lv_ta_set_one_line",the object “ta” can still input "Enter",I think it's Incorrect.

**Comment by kisvegabor** [comment]
Hi,

I tested it with this:
```c
    lv_obj_t * ta = lv_ta_create(lv_scr_act(), NULL);
    lv_ta_set_one_line(ta, true);
    lv_ta_set_text(ta, "a\nb");
```

And got: 
![image](https://user-images.githubusercontent.com/7599318/43049602-ad696d86-8dfa-11e8-8754-e61657403969.png)

So the most simple code above worked correctly. Can you provide a code snippet which shows a not -working scenario?

**Comment by as564335sa** [comment]
Hi,
My code is the same as yours，The difference is that I use external keyboard or “kb” object to input "Enter" instead of using "lv_ta_set_text" API;
This my code:
`
lv_obj_t *ta;
ta = lv_ta_create(cont,NULL);
lv_ta_set_one_line(ta,true);
lv_obj_align(ta,cont,LV_ALIGN_CENTER,0,0);
lv_obj_set_size(ta,200,20);
lv_ta_set_style(ta,LV_TA_STYLE_BG,&cont_style);
lv_ta_set_text(ta,"0");
lv_group_add_obj(group,ta);
`

When pressing the “Enter” key, the cursor of the “ta” object jumps to the next line of "text"

**Comment by kisvegabor** [comment]
Hi,

Finally, I find the bug. It was more complicated than it seems because LittlevGL tried to ignore line breaks in the case of Text area but - as you can see - it failed in some cases. 

Now I simplified it and `\n` characters are just ignored in `lv_ta_add_char`.
The update is in `dev-5.2` branch.

Please verify if it works!
