### ISSUE TITLE
shaddow in 480x272 lcd

### ISSUE THREAD

**Issue by relliktei** [lvgl/lvgl#323]
I try to use littlevgl 5.1 in my STM32F429ZGT6 board(with 8M sdram, 480 x 272 lcd display), but I got some bugs, as following picture,  but have no idea to fix .
Could you please give me some idea?

![shadow](https://user-images.githubusercontent.com/41564775/43060531-efca4676-8e83-11e8-98a1-7cbf66f91bcd.png)

**Comment by BesitzeRuf** [comment]
Hi **relliktei** What model of LCD are you using? How it is connected (spi, rgb, fmc, etc.. )? Can you just simply draw rectangles with different colors? If you are running "demo" examples, there is 99% chance, that the bug is not caused by library. For now with provided information the problem can be: in LCD itself, in cables (I see some dupont cables), bad settings in initialization ... and many more things...

**Comment by kisvegabor** [comment]
Hi,

I also suggest drawing colored rectangles (using only your LCD driver) next to each other or put only colored pixels on random places.

@BesitzeRuf 
> there is 99% chance, that the bug is caused by library. 

For me, it seems it's 99% that it's NOT caused by the library. Is it typo or do you think it's probably a library issue?

**Comment by BesitzeRuf** [comment]
@kisvegabor  Aaaa... Sorry, it is typo of-course. This demo example had been tested many times by many people and works perfectly.

**Comment by relliktei** [comment]
@BesitzeRuf @kisvegabor
Thanks for your suggestion, I solved this problem after I changed rgb lcd cable.
