### ISSUE TITLE
Button style is implicitly updated when actions occur.

### ISSUE THREAD

**Issue by nameofuser1** [lvgl/lvgl#335]
It looks like buttons are redrawn on the screen when action occurs regardless of their explicit modifications. I understand that this behavior allows to update styles without handling events explicitly. However I think it would be better if there was a feature that allows to explicitly specify whether I would like to change the style on event or not. This can be justified by the fact that using slow LCD screens and updating UI elements without any changes in their style looks quite awful.

As a solution I would propose to create additional field, something like `update_style_on_event`, and functions which will set and clear this flag. In signal processing function check for this flag and redraw only if needed.

**Comment by kisvegabor** [comment]
Hi,

As you said the button is redrawn because a new style is set for it on press/release. The `lv_obj_style()` function will invalidate the button. But if we added a line to `lv_obj_set_style` to invalidate the object only if the new style is different from the current the problem would be solved by setting the same style in pressed and released state.

What do you think?

**Comment by nameofuser1** [comment]
Didn't notice that styles are saved as pointers. Yes, I agree this would be a better solution.

**Comment by kisvegabor** [comment]
Great!

Then please add `if(obj->style_p == style) return;` to the very beginning of `lv_obj_set_style` and let's see if it's help.

**Comment by kisvegabor** [comment]
Implemented in #352 Pull request.

Thank you!
