### ISSUE TITLE
Symbol font update

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lvgl#34]
I've optimized the font storage to use less memory. 
@ajaybhargav please generate the symbol fonts again with the new python script: https://github.com/littlevgl/utils/blob/beta/font_create/fnt2c.py

Usage: 
`python fnt2c.py -f <font_name> [-o <output file> -s <start unicode> -e <end unicide>]`

Or see `python fnt2c.py -h` for a detailed explanation.

If you have no time right now to deal with it just send me the fnt and png files and I will do this.

Thank you in advance!

**Comment by ajaybhargav** [comment]
Hi Gabor,
I am attaching Symbol_30 and Symbol_60 fnt + png files. I have got lot of work piled up due to holidays and it doesn't seem like ending soon.

Let me know if you need anything else.

[font_create.zip](https://github.com/littlevgl/lvgl/files/1348338/font_create.zip)

![symbol_60_0](https://user-images.githubusercontent.com/927133/31070086-bcb69ce2-a77c-11e7-8524-67ff82a74c51.png)

![symbol_30_0](https://user-images.githubusercontent.com/927133/31070085-bcb55224-a77c-11e7-9a0d-23cb806e90e7.png)

**Comment by ajaybhargav** [comment]
I am also attaching config files used for creating fonts. So it will be easier for you.

[font_create_config.zip](https://github.com/littlevgl/lvgl/files/1348343/font_create_config.zip)

**Comment by kisvegabor** [comment]
Thank you very much! 
And good luck in your work!

**Comment by ajaybhargav** [comment]
Thank you! 👨‍💻
