### ISSUE TITLE
Gauge object generates unaligned lines for dividers

### ISSUE THREAD

**Issue by mrkvtrs** [lvgl/lvgl#344]
Couple problems with the gauge that makes it appears to be very imprecise.

1 On the gauge it seems that dividers have different directions instead to be directed to the center of the gauge. 
2 The dividers for labels and lines are not aligned between each other. For example I set the following configuration:
`lv_gauge_set_scale(manometer_obj, angle , 60, 12);` - it means that between each divider with text should be 4 small dividers. But it is not. See attached picture.
![gauge](https://user-images.githubusercontent.com/39525092/43489275-802056fe-94ea-11e8-9e6e-6f01148a46c1.png)

Is that possible to fix? How much effort it needs?

**Comment by kisvegabor** [comment]
Hi,

I tested it and it really not works as it should. I will examine it soon.

Thank you for the report.

**Comment by kisvegabor** [comment]
Hi, 
I examined the issue. It was because of the bad `line_cnt` value in `lv_gauge_set_scale`.
I added the equation to the API comment about how to calculate `line_cnt` if you know the desired number of subdivision lines: `line_cnt = (sub_div + 1) * (label_cnt - 1) + 1`. So in your case it's 56.

With the direction of the lines, half pixel error always can happen because of rounding. 

![image](https://user-images.githubusercontent.com/7599318/45011122-35e60600-b011-11e8-80a8-f6cbfb47611f.png)
