### ISSUE TITLE
Rotary encoder, push button

### ISSUE THREAD

**Issue by sokolbiba** [lvgl/lvgl#365]
Hi everyone,
I am new to the LittleVGL and I am trying to understand how it deals with hardware push buttons and rotary encoders. I checked that in the documentation and found nothing about this.  Can you please share with me some examples or a step by step guide how to deal with that. 
Regards,
Sokol

**Comment by kisvegabor** [comment]
Hi,

There are some updates to make the use of a rotary encoder more simple but it's not documented yet because it will be released in v5.2 (the next release).

In nutshell:
1. Use the `dev-5.2` branch
2. Read this to see how the keyboard navigation works now: https://littlevgl.com/basics#touchad-less-navigation
3. In your encoder read function assign: `LV_GROUP_KEY_LEFT/RIGHT` to left/right turn and `LV_GROUP_KEY_ENTER` to the button
3. Edit and navigate modes are introduced for `lv_group`. In navigate mode: LV_GROUP_KEY_LEFT/RIGHT will move to the next object. In edit mode: it will change the value of the object.  Enable it in the group with: `lv_group_enable_edit(g, true);` Not that there is nothing to edit on an object, like a button it won't go to edit mode, but e.g. slider will.
4. You can test it with `lv_test_group_1()` if you add `lv_group_enable_edit(g, true);` after `g = lv_group_create();` (I suggest to use the PC simulator first)

Please let me know how it worked!

**Comment by sokolbiba** [comment]
Hi, 
Thank you for reply. Somehow I see it more easier to deploy the library in the MCU instead of the PC. For the moment somehow I solved it by calling lv_group_focus_prev(group) and lv_group_focus_next(group) directly in the FTM interrupt. I am using the FTM as quadradure decoder.  Here is the code:

void FTM1_IRQHandler(void)
{
	FTM_ClearStatusFlags(FTM_1_PERIPHERAL,kFTM_TimeOverflowFlag);
	BaseType_t xHigherPriorityTaskWoken = pdFALSE;
	if (FTM_GetQuadDecoderFlags(FTM_1_PERIPHERAL) & kFTM_QuadDecoderCountingIncreaseFlag)
	{
		PRINTF("PREV\n");
		lv_group_focus_prev(g);  // navigate to prev
	}
	else
	{
		lv_group_focus_next(g);//navigate to next
		PRINTF("NEXT\n");
	}
	portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}
Can I assign the window btn to a group? Lets say a close button is needed. How can I close the window after I have been navigating all the group elements?

**Comment by kisvegabor** [comment]
Hi,

I see. Thank you for sharing your solution! 
(You can put your code between ` ```c ` your code ` ``` ` tags to give it syntax highlight.

`lv_win_add_btn()` returns a pointer to the created button which can be simply added to a group.

As you solved the original question I close this issue. If you have other question related to the window's buttons please open a new issue for it.
