### ISSUE TITLE
Suggestion for change to lv_btn_set_styles

### ISSUE THREAD

**Issue by scopa90** [lvgl/lvgl#39]
First of all I am working with the latest beta and can see many many improvements.  Two immediate changes are that fonts are clearer and the code seems smaller so thank you for that.

Would it be an idea to allow lv_btn_set_styles to use NULL for button styles which are not to be changed and just supply the ones you want to alter? Or is there already a function to do this?

**Comment by kisvegabor** [comment]
I'm glad to hear that you like the new improvements.

It's a good idea to leave the style of given state unchanged when set to NULL.
  
I have a constructive idea. Because it is super easy to implement in `lv_btn_set_styles` function I suggest that add this improvement yourself and then create a pull request on GitHub. It would be good for both of us because an extra contribution is always welcome! :)

Please quickly read this document before modyfing code: https://github.com/littlevgl/lvgl/blob/master/docs/CONTRIBUTING.md#formatting

**Comment by scopa90** [comment]
Oddly enough I've made the changes in my copy and was going to send over a small patch file.  The only possible issue with the pull request is the include paths - if you recall I've mentioned this in the past and my copy is setup for my project with misc and misc under lvgl. Let me read through the doc you've linked to and I'll see if it's possible.

**Comment by kisvegabor** [comment]
I see. Maybe try this to commit only specific parts of a file: https://stackoverflow.com/questions/1085162/commit-only-part-of-a-file-in-git
It might be useful later too.

Anyway I wouldn't like to cause to much pain with this. If it's too difficult to contribute in this way I can also add the update.
