### ISSUE TITLE
Duplicated LV_FONT_DEFAULT in configuration file

### ISSUE THREAD

**Issue by ErichStyger** [lvgl/lvgl#446]
Hi,
In the latest lv_conf_templ.h the following define is present twice:
LV_FONT_DEFAULT
One of them should be removed.

Created pull request for it:
https://github.com/littlevgl/lvgl/pull/445

Thanks,
Erich

**Comment by kisvegabor** [comment]
Hello,

I merged your PR. Thank you!

I'm planning to move the documentation of LittlevGL from the website to
GitHub wiki. Mainly it means copy pasting and reviews. Would you be
interested in it?
I will open an issue on GitHub to get help in it.

Best regards,
Gabor

On 6 Oct 2018 10:48, "Erich Styger" <notifications@github.com> wrote:

Hi,
In the latest lv_conf_templ.h the following define is present twice:
LV_FONT_DEFAULT
One of them should be removed.

Created pull request for it:
#445 <https://github.com/littlevgl/lvgl/pull/445>

Thanks,
Erich

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/littlevgl/lvgl/issues/446>, or mute the thread

**Comment by ErichStyger** [comment]
Having the documentation on Git is a good idea. For sure I help if I can. My time will be limited, but if I spot something or if I have anything to add, I'm happy to contribute.
