### ISSUE TITLE
New object idea : number spin box 

### ISSUE THREAD

**Issue by AloyseTech** [lvgl/lvgl#485]
I'm looking for a way to display and enter number in a given range. I'm used to Qt and the QSpinBox object. It seems that it could be an extension of a text area, but with a validator for numeric characters only and special action on some keys (KEY_UP and KEY_DOWN would increase/decrease the number by a given STEP amount, which could be an integer of a float).

**Comment by embeddedt** [comment]
You can use `lv_ta_set_accepted_chars` to set the list of accepted characters to digits only.

There isn't an API for changing the behavior of the up and down keys, but you could write your own signal function that checks for the up or down keys before passing the result to the original ancestor signal function.

Have a look at the text area signal function here (you'll have to click the link otherwise it only shows one line):

https://github.com/littlevgl/lvgl/blob/88b8e982b485368cc873860ba602a4cd315d674f/lv_objx/lv_ta.c#L1084

And lastly, if you wanted a more classic spinbox, you could add two buttons and give them up and down arrows.

**Comment by AloyseTech** [comment]
I already have a validator for the charset (""1234567890.+-"). I will investigate the signal handler modification, thanks

**Comment by kisvegabor** [comment]
I agree with @embeddedt  the signal function can be used to overwrite the current behavior. 

@AloyseTech If you are interested you can even add a new object type based on the Text area. However, modifying the signal function is much more simple.

**Comment by AloyseTech** [comment]
I'm actually trying to create a new object, since it seems to be more appropriate since the spinbox should have specific additional parameters.

**Comment by embeddedt** [comment]
@AloyseTech Are you making a new object with a custom design function, or making a new object that will have a button, text area, etc. as children?

**Comment by AloyseTech** [comment]
I’ve made a copy of the ta object and started modifying it. I’ve not been far at the moment though. Only modified the structure parameter and getter/setters.

**Comment by kisvegabor** [comment]
@embeddedt I agree. If a new object type should work like an existing one than the new object should be inherited from the existing.  In this case, the Text area seems a good ancestor only it's signal function need to be modified.

**Comment by AloyseTech** [comment]
I have created an object which extends Text Area (as ancestor). Here is what I've got at the moment :
![lv_spinbox](https://user-images.githubusercontent.com/13847288/47790282-0b65b000-dd17-11e8-9ac0-0b30a87e8a19.gif)
I use an encoder as input device, as well as 2 hardware buttons to navigate between digits.

**Comment by kisvegabor** [comment]
@AloyseTech Wow, looks awesome! Congratulations! Can you create a PR?

**Comment by AloyseTech** [comment]
@kisvegabor thanks. I will create a PR

**Comment by AloyseTech** [comment]
It is in the documentation. The doc page is not complete but the test code is available.
