### ISSUE TITLE
Disabling cursor on text area when focused but not editable (set active only in edit mode)

### ISSUE THREAD

**Issue by AloyseTech** [lvgl/lvgl#509]
Hi,

I think the cursor should be hidden when a Text Area is focused in a group but not yet selected for edition.

One might consider the text area editable as soon as the cursor is active and blinking.

Currently the cursor is visible both in focused and edition mode.
The signal LV_SIGNAL_FOCUS should not enable the cursor. The cursor should be set to visible when the signal LV_SIGNAL_GET_EDITABLE is caught. It seems, however, that there is no signal indicating the end of edition that could be used to disable the cursor...

EDIT: After digging a bit it would be great if each object could have an edit flag.

**Comment by kisvegabor** [comment]
Hi,

> It seems, however, that there is no signal indicating the end of edition that could be used to disable the cursor...

`LV_SIGNAL_FOCUS` is sent when the edit mode has changed too. See `lv_group_set_editing`. So in the FOCUS signal we can check the edit state to decide what to do with the cursor.

But what if a virtual keyboard (`lv_kb`) is writing to the Text area. In this case, the keyboard is in focus so cursor won't be displayed. Now, `lv_kb` clears the `LV_CURSOR_HIDDEN` flag to show the otherwise hidden cursor.

**Comment by AloyseTech** [comment]
Do you plan tu add the edit flag in each editable object? We could maybe imagine a way to let the text area “know” when it is edited but not in focus.

**Comment by kisvegabor** [comment]
I think the edit flag is not required because we can do something similar like the in `lv_ddlist`: https://github.com/littlevgl/lvgl/blob/master/lv_objx/lv_ddlist.c#L528

However, I agree if an encoder is focused the `ta`  and it's not in edit mode then the cursor shouldn't be drawn. But it should be drawn if a `KEYPAD` focuses the `ta` where there is no edit/navigate mode

**Comment by AloyseTech** [comment]
The same solution as in the ddlist could be used, indeed. Do you plan to implement this functionality?

**Comment by kisvegabor** [comment]
Great! I'll add it in a few days.

**Comment by kisvegabor** [comment]
Hi,

I added this feature: https://github.com/littlevgl/lvgl/commit/2a053b86bfe8726a2055ce38e4b3a1cbb6933a0e

**Comment by AloyseTech** [comment]
I tested it with my GUI but it does not work as I expected. Currently I have a button "done" to stop editing a spinbox. When it is clicked I call `lv_group_remove_obj(spinbox);` to remove it from my single object group. It seems that LV_SIGNAL_FOCUS is not sent at this point and so the cursor stays visible. The style goes back to normal though.

**Comment by kisvegabor** [comment]
The spinbox is the only object in the group?

**Comment by AloyseTech** [comment]
Yes it is.

**Comment by embeddedt** [comment]
I assume this issue is resolved so I will close it. If you continue to experience problems feel free to reopen the issue.
