### ISSUE TITLE
A bug in new LVGL build.

### ISSUE THREAD

**Issue by mrkvtrs** [lvgl/lvgl#556]
In my project the issue us reproduced when the User interface shows the mbox. After press Ok button I am getting a hardfault.

In the debug mode I can successfully exit from the mbox callbaxk function. Then I endup in the lv_btnm.c file, line 564. The btn_id_pr variable is 0xFFFF (LV_BTNM_PR_NONE) - which I think is valid number. 
But the code below in there is doing next:
`lv_area_copy(&btn_area, &ext->button_areas[ext->btn_id_pr]);` that is actuallu exposed to next:
`memcpy(dest, src, sizeof(lv_area_t));`

The src is the `&ext->button_areas[65535]` - and it is far away from the memory region assigned to the work_mem.
This looks like a bug in the library.

The code that I am using for mboxes:
```
lv_res_t common_mbox_callback(lv_obj_t * btns, const char * txt)
{
    lv_obj_t * mbox = lv_mbox_get_from_btn(btns);
    lv_obj_t * gray_bg = lv_obj_get_parent(mbox);
    lv_obj_del(gray_bg);

    main_data.usb_connection_msg_shown    = 0;

    keypad_update(prev_group);
    lv_group_del(mbox_key_group);

    return LV_RES_OK;
}
void ui_display_warning_message(const char * msg)
{
    static lv_style_t gray_style;
    lv_style_copy(&gray_style, &lv_style_plain);
    gray_style.body.opa = LV_OPA_70;
    gray_style.body.main_color = LV_COLOR_HEX3(0x111);
    gray_style.body.grad_color = LV_COLOR_HEX3(0x111);

    lv_obj_t * gray_bg = lv_obj_create(lv_scr_act(), NULL);
    lv_obj_set_style(gray_bg, &gray_style);
    lv_obj_set_size(gray_bg, LV_HOR_RES, LV_VER_RES);

    static const char * btns[] = {"Ok", ""};

    lv_obj_t * mbox = lv_mbox_create(gray_bg, NULL);
    lv_mbox_set_text(mbox,msg);
    lv_mbox_add_btns(mbox, btns, common_mbox_callback);
    lv_obj_align(mbox, NULL, LV_ALIGN_CENTER, 0, 0);

    prev_group = keypad_get_group();
    mbox_key_group = lv_group_create();
    lv_group_add_obj(mbox_key_group, mbox);
    keypad_update(mbox_key_group);
}
```
I tried it in another project where I have almost zero objects and it worked. Only because the pointer was pointing to valid memory address.

**Comment by embeddedt** [comment]
@TMarkivULCRobotics Haven't reproduced this on my end, but from a preliminary glance at the source code of `lv_btnm.c`, your description of the issue seems impossible!

https://github.com/littlevgl/lvgl/blob/7528e2a9b2282078d185465ada6e002594e40c7a/lv_objx/lv_btnm.c#L559

This line is where the callback is invoked. Note that it is wrapped in an if statement checking if `btn_id_pr != LV_BTNM_PR_NONE`.

https://github.com/littlevgl/lvgl/blob/7528e2a9b2282078d185465ada6e002594e40c7a/lv_objx/lv_btnm.c#L564

This is the line you described as being the location of the hard fault. Note that it is still inside the if statement, so (unless I missed something) it should never be copying from `ext->button_areas[LV_BTNM_PR_NONE]`.

Possibly `btn_id_pr` is being overwritten inside your callback (stack overflow?). Maybe you could try setting breakpoints before and after `ext->action` is called on line 559 and see if the value changes.
