### ISSUE TITLE
uint64_t used as pointer address type

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lvgl#574]
I think the use of `uint64_t` as an address on this line and in other locations within this file is nonportable and should be avoided. Maybe `uintptr_t` should be used instead.

https://github.com/littlevgl/lvgl/blob/2c8cf7d7ea341ff524b0d021d69b229357bdc06a/lv_themes/lv_theme.c#L76

**Comment by C47D** [comment]
+1 for using `uintptr_t` see [this](https://stackoverflow.com/a/49617592), AFAIK `uintptr_t` it's available since C99 tho.

**Comment by kisvegabor** [comment]
I agree we can use `uintptr_t`. It's really more elegant.

**Comment by embeddedt** [comment]
@C47D I think that most modern embedded compilers support C99, and in the worst case the user can simply `typedef` `uint64_t` themselves.

**Comment by kisvegabor** [comment]
@embeddedt 
Will you create a Pull request?

**Comment by embeddedt** [comment]
@kisvegabor I will, but it will be later today.

**Comment by kisvegabor** [comment]
Great, thank you!

**Comment by C47D** [comment]
I can't find the issue were @aenchevich and @kisvegabor were discussing about using C99 features and leave C90 behind, i guess it's time to do so (if everybody agree).

**Comment by kisvegabor** [comment]
@C47D 
I remember that conversation. For maximal compatibility, we should use only the most important and most widely adopted features of C99. For example: `for(int i = 0; i < 10; i++)` is still not working in a lot of compilers.
Anyway, using `uintptr_t` is quite reasonable. And in case of incompatibility, it can be fixed with a typedef (as @embeddedt mentioned)

@embeddedt 
Thank you for the fix!
