### ISSUE TITLE
Can you separate out the anti-aliasing line part of your code?

### ISSUE THREAD

**Issue by yihua-wang** [lvgl/lvgl#655]
I want to learn the algorithm of LCD linear anti-aliasing.

**Comment by kisvegabor** [comment]
The basic idea is to get the integer points of the line with [Bresenham's line drawing algorith](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm) and when a horizontal line steps one in y-direction add translucent pixels with linearly increasing/decreasing opacity on the edges. It doesn't give a perfect result but it's fast and good enough for almost all cases.

The things become much more complicated because of the perpendicular line ending. So, in fact, the line is built up from small "ending parts". Basically, the line ending is repeated but it's quite difficult to explain in a few lines. 

Anyway, the drawing functions are not designed to be modular and to be separated from the library. However, they are using [these function pointers](https://github.com/littlevgl/lvgl/blob/master/lv_draw/lv_draw.h#L91). So maybe you can separate them if you provide the same interface functions.
