### ISSUE TITLE
Shape of round buttons not round

### ISSUE THREAD

**Issue by harteware07** [lvgl/lvgl#938]
I designed some round buttons, all the used styles have the  ` .body.radius = LV_RADIUS_CIRCLE;` argument. 
I added a screenshot of the simulator, the behaviour is the same on the hardware. Version is 5.3

![grafik](https://user-images.githubusercontent.com/1401220/54121423-acb5ee80-43fa-11e9-90e1-9fd1783aa737.png)

```c
for(uint8_t i = 0, k = 0; i < 7; i++) {
btnCalDays[i] = lv_btn_create(bg_edit, NULL);
		lv_obj_set_size(btnCalDays[i], 40, 40);
		lv_btn_set_style(btnCalDays[i], LV_BTN_STYLE_REL, &bg_style);
		lv_btn_set_style(btnCalDays[i], LV_BTN_STATE_PR, &indic_style);
		lv_btn_set_style(btnCalDays[i], LV_BTN_STATE_TGL_REL, &indic_style);
		lv_btn_set_style(btnCalDays[i], LV_BTN_STYLE_TGL_PR, &indic_style);
		lv_btn_set_style(btnCalDays[i], LV_BTN_STYLE_INA, &knob_style);
		lv_btn_set_toggle(btnCalDays[i], 1);
		lv_obj_set_free_num(btnCalDays[i], (1<<i));
		lv_btn_set_action(btnCalDays[i], LV_BTN_ACTION_CLICK, gui_scenes_edit_calendar);
}
```

You can see that the circles are not drawn smoothly but have "stairs" in them. Have you observed this behaviour and is there a solution for it?

Thanks again!

**Comment by embeddedt** [comment]
I think that this behavior is not abnormal (and I've seen it in other places), but @kisvegabor knows more about how the antialiasing works than I do.

**Comment by harteware07** [comment]
imho it's not the antialiasing, it' the algorithm that calculates the roundness that produces the edges

**Comment by embeddedt** [comment]
@harteware07 Try turning off antialiasing and see whether the circle looks round.

**Comment by kisvegabor** [comment]
I've played with a little and improved the circle's anti-aliasing. 

It's still not perfect but it's the limitation of the curernt algorithm because due to rounding errors some parts of the circle results in lines:

![image](https://user-images.githubusercontent.com/7599318/55058453-483a9680-506c-11e9-8ca8-b8022bd9ba47.png)
![image](https://user-images.githubusercontent.com/7599318/55058690-fba38b00-506c-11e9-8dcf-67b33a5b8918.png)

If you want to imrove it, the relevant code is here: https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_draw/lv_draw_rect.c#L1422

Feel free to reopen this issue if you have found better paramters.
